# Controls behaviors pertaining to the way Privblur requests Tumblr
[privblur_backend]
    # Timeout for requests to Tumblr's API
    main_response_timeout = 10

    # Timeout for fetching image responses from Tumblr 
    image_response_timeout = 30