# Controls deployment options
[deployment]
    host = "127.0.0.1"
    port = 8000

    # Amount of worker Privblur instances to spawn. Increases speed significantly.
    workers = 1

    # If you're running Privblur behind a remote proxy, one or more of the following must be set
    # can also be set via env variables by captialzing and prefixing with PRIVBLUR_

    # For more information see
    # https://sanic.dev/en/guide/advanced/proxy-headers.html
    forwarded_secret = ""
    real_ip_header = ""
    proxies_count = ""

# Controls behaviors pertaining to the way Privblur requests Tumblr
[privblur_backend]
    # Timeout for requests to Tumblr's API
    main_response_timeout = 10

    # Timeout for fetching image responses from Tumblr 
    image_response_timeout = 30


# Controls logging behavior
#
# Use Python's numerical logging levels
# https://docs.python.org/3/howto/logging.html#logging-levels
[logging]
    # Sanic (Server)'s logging level'
    sanic_logging_level = 30

    # Privblur's logging level
    privblur_logging_level = 30

    # Privblur extractor's logging level
    privblur_extractor_logging_level = 20

[misc]
    # Enable sanic's dev mode
    dev_mode=false