version: "3"
services:
  priviblur:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./config.toml:/priviblur/config.toml:Z,ro

